version: '3.8'

services:
  node-app:
    build: ./node-app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./node-app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    command: ["sh", "-c", "pm2 start server.js --name myapp && npm install && node watch.js"]

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
